// <auto-generated />
using Mango.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.CouponAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260920151830_AddCouponToDb")]
partial class _20260920151830_AddCouponToDb
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.CouponAPI.Models.Coupon", b =>
            {
                var couponId = b.Property<int>("CouponId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(couponId);

                b.Property<string>("CouponCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("DiscountAmount")
                    .HasColumnType("float");

                b.Property<int>("MinAmount")
                    .HasColumnType("int");

                b.HasKey("CouponId");

                b.ToTable("Coupons");

                b.HasData(
                    new
                    {
                        CouponId = 1,
                        CouponCode = "10OFF",
                        DiscountAmount = 10.0,
                        MinAmount = 20
                    },
                    new
                    {
                        CouponId = 2,
                        CouponCode = "20OFF",
                        DiscountAmount = 20.0,
                        MinAmount = 50
                    });
            });
#pragma warning restore 612, 618
    }
}
