// <auto-generated />
using System;
using Mango.RewardsAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.RewardsAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260929025803_AddRewardsToDb")]
partial class _20260929025803_AddRewardsToDb
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.RewardsAPI.Models.Rewards", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<int>("OrderId")
                    .HasColumnType("int");

                b.Property<int>("RewardsActivity")
                    .HasColumnType("int");

                b.Property<DateTime>("RewardsDate")
                    .HasColumnType("datetime2");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Rewards");
            });
#pragma warning restore 612, 618
    }
}
