@Mango.ProductAPI_HostAddress = http://localhost:5128

GET {{Mango.ProductAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Mango.ProductAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
