// <auto-generated />
using System;
using Mango.OrderAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.OrderAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260928194947_AddOrderToDB")]
partial class _20260928194947_AddOrderToDB
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.OrderAPI.Models.OrderDetails", b =>
            {
                var orderDetailsId = b.Property<int>("OrderDetailsId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(orderDetailsId);

                b.Property<int>("Count")
                    .HasColumnType("int");

                b.Property<int>("OrderHeaderId")
                    .HasColumnType("int");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.Property<string>("ProductName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("OrderDetailsId");

                b.HasIndex("OrderHeaderId");

                b.ToTable("OrderDetails");
            });

        modelBuilder.Entity("Mango.OrderAPI.Models.OrderHeader", b =>
            {
                var orderHeaderId = b.Property<int>("OrderHeaderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(orderHeaderId);

                b.Property<double>("CartTotal")
                    .HasColumnType("float");

                b.Property<string>("CouponCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<double>("Discount")
                    .HasColumnType("float");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("OrderTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Phone")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("OrderHeaderId");

                b.ToTable("OrderHeader");
            });

        modelBuilder.Entity("Mango.OrderAPI.Models.OrderDetails", b =>
            {
                b.HasOne("Mango.OrderAPI.Models.OrderHeader", "OrderHeader")
                    .WithMany("OrderDetails")
                    .HasForeignKey("OrderHeaderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("OrderHeader");
            });

        modelBuilder.Entity("Mango.OrderAPI.Models.OrderHeader", b =>
            {
                b.Navigation("OrderDetails");
            });
#pragma warning restore 612, 618
    }
}
