@Mango.AuthAPI_HostAddress = http://localhost:5103

GET {{Mango.AuthAPI_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{Mango.AuthAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
