// <auto-generated />
using Mango.ShoppingCartAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.ShoppingCartAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260925014857_AddShoppingCartToDb")]
partial class _20260925014857_AddShoppingCartToDb
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.ShoppingCartAPI.Models.CartDetails", b =>
            {
                var cartDetailsId = b.Property<int>("CartDetailsId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(cartDetailsId);

                b.Property<int>("CartHeaderId")
                    .HasColumnType("int");

                b.Property<int>("Count")
                    .HasColumnType("int");

                b.Property<int>("ProductId")
                    .HasColumnType("int");

                b.HasKey("CartDetailsId");

                b.HasIndex("CartHeaderId");

                b.ToTable("CartDetails");
            });

        modelBuilder.Entity("Mango.ShoppingCartAPI.Models.CartHeader", b =>
            {
                var cartHeaderId = b.Property<int>("CartHeaderId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(cartHeaderId);

                b.Property<string>("CouponCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CartHeaderId");

                b.ToTable("CartHeaders");
            });

        modelBuilder.Entity("Mango.ShoppingCartAPI.Models.CartDetails", b =>
            {
                b.HasOne("Mango.ShoppingCartAPI.Models.CartHeader", "CartHeader")
                    .WithMany()
                    .HasForeignKey("CartHeaderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CartHeader");
            });
#pragma warning restore 612, 618
    }
}
