// <auto-generated />
using System;
using Mango.EmailAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.EmailAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260928150350_AddEmailToDb")]
partial class _20260928150350_AddEmailToDb
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.EmailAPI.Models.EmailLogger", b =>
            {
                var id = b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(id);

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("EmailSent")
                    .HasColumnType("datetime2");

                b.Property<string>("Message")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("EmailLogger");
            });
#pragma warning restore 612, 618
    }
}
