// <auto-generated />
using Mango.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.ProductAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260924014421_ReplaceImageUrlWithFileName")]
partial class _20260924014421_ReplaceImageUrlWithFileName
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.ProductAPI.Models.Product", b =>
            {
                var productId = b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(productId);

                b.Property<string>("CategoryName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageFileName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.HasKey("ProductId");

                b.ToTable("Products");

                b.HasData(
                    new
                    {
                        ProductId = 1,
                        CategoryName = "Appetizer",
                        Description = "Grilled bread rubbed with garlic and topped with fresh tomato, basil, and olive oil.",
                        Name = "Bruschetta",
                        Price = 8.9900000000000002
                    },
                    new
                    {
                        ProductId = 2,
                        CategoryName = "Appetizer",
                        Description = "Sliced tomatoes and fresh mozzarella layered with basil and a balsamic drizzle.",
                        Name = "Caprese Salad",
                        Price = 9.9900000000000002
                    },
                    new
                    {
                        ProductId = 3,
                        CategoryName = "Appetizer",
                        Description = "Oven-baked Italian flatbread with rosemary, sea salt, and olive oil.",
                        Name = "Focaccia Bread",
                        Price = 6.9900000000000002
                    },
                    new
                    {
                        ProductId = 4,
                        CategoryName = "Main Course",
                        Description = "Classic Roman pasta tossed with Pecorino Romano and cracked black pepper.",
                        Name = "Cacio e Pepe",
                        Price = 15.99
                    },
                    new
                    {
                        ProductId = 5,
                        CategoryName = "Main Course",
                        Description = "Wood-fired pizza with San Marzano tomatoes, fresh mozzarella, and basil.",
                        Name = "Margherita Pizza",
                        Price = 14.99
                    },
                    new
                    {
                        ProductId = 6,
                        CategoryName = "Main Course",
                        Description = "Pasta tossed in a vibrant basil pesto with pine nuts and Parmesan.",
                        Name = "Pesto Pasta",
                        Price = 15.49
                    },
                    new
                    {
                        ProductId = 7,
                        CategoryName = "Main Course",
                        Description = "Wood-fired pizza topped with basil pesto, mozzarella, and cherry tomatoes.",
                        Name = "Pesto Pizza",
                        Price = 16.489999999999998
                    },
                    new
                    {
                        ProductId = 8,
                        CategoryName = "Main Course",
                        Description = "Pasta in a rich San Marzano tomato sauce with fresh basil and garlic.",
                        Name = "Pomodoro Pasta",
                        Price = 13.99
                    },
                    new
                    {
                        ProductId = 9,
                        CategoryName = "Main Course",
                        Description = "Handmade ravioli filled with ricotta and spinach in a sage butter sauce.",
                        Name = "Spinach Ravioli",
                        Price = 16.989999999999998
                    },
                    new
                    {
                        ProductId = 10,
                        CategoryName = "Dessert",
                        Description = "Crisp pastry shell filled with sweetened ricotta and chocolate chips.",
                        Name = "Cannolo",
                        Price = 7.9900000000000002
                    },
                    new
                    {
                        ProductId = 11,
                        CategoryName = "Dessert",
                        Description = "Silky vanilla bean panna cotta topped with a fresh berry compote.",
                        Name = "Panna Cotta",
                        Price = 7.4900000000000002
                    },
                    new
                    {
                        ProductId = 12,
                        CategoryName = "Dessert",
                        Description = "Layers of espresso-soaked ladyfingers and mascarpone cream, dusted with cocoa.",
                        Name = "Tiramisu",
                        Price = 8.4900000000000002
                    });
            });
#pragma warning restore 612, 618
    }
}
