// <auto-generated />
using Mango.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.ProductAPI.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260924011319_AddProductToDb")]
partial class _20260924011319_AddProductToDb
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Mango.ProductAPI.Models.Product", b =>
            {
                var productId = b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(productId);

                b.Property<string>("CategoryName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageLocalPath")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.HasKey("ProductId");

                b.ToTable("Products");

                b.HasData(
                    new
                    {
                        ProductId = 1,
                        CategoryName = "Main Course",
                        Description = "Tender chicken tikka glazed with mango chutney.",
                        Name = "Mango Chicken Tikka",
                        Price = 14.99
                    },
                    new
                    {
                        ProductId = 2,
                        CategoryName = "Beverage",
                        Description = "Chilled yogurt drink blended with fresh mango.",
                        Name = "Mango Lassi",
                        Price = 4.9900000000000002
                    });
            });
#pragma warning restore 612, 618
    }
}
